---
default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
        files: \.(conf|j2|js|json|rb|md|py|sh|tf|tm?pl|txt|yaml|yml)$
      - id: check-case-conflict
      - id: check-json
        exclude: 'env_variables\.json$|jenkins-master\.json$|nexus\.json$'
      - id: check-toml
      - id: end-of-file-fixer
        exclude: '^\.idea/.*$'
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
        exclude: 'docker-compose/.*\.yaml$'
  - repo: https://github.com/Yelp/detect-secrets.git
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        args:
          - '--baseline'
          - '.secrets.baseline'
        exclude: 'package-lock\.json$|Pipfile\.lock$|^.secrets.baseline$'
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: shellcheck
        exclude: 'gradlew$'
      - id: shfmt
        exclude: 'gradlew$'
        args:
          - '-w -i 2 -ci -bn -sr'
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        args:
          - '--config'
          - '.black'
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
      - id: editorconfig-checker-system
        alias: ec
